# APS106 - Fundamentals of Computer Programming
## Week 12 | Lecture 1 (12.1) - Installing third-party packages, managing environments, and Pandas

### This Week
| Lecture | Topics |
| --- | --- |
| **12.1** | **Pandas** |
| 12.2 | More Pandas, Data Visualization | 
| 12.3 | Design Problem: Stock Market, Part 1 |

### Lecture Structure
1. [csv Module](#section1)
2. [DataFrames](#section2)
3. [Breakout Session 1](#section3)
4. [Series](#section4)
5. [Data Extraction](#section5)
6. [Breakout Session 2](#section6)
7. [Looping](#section7)
8. [Saving DataFrames](#section8)

<a id='section1'></a>
## 1. csv Module
Let's first import the `csv` module, that comes pre-installed with Python.

In [1]:
import csv

We will now import a `csv` file which contains the results from past presidential elections in the United States. This file is in the same folder as this notebook and is named `elections.csv`.

In [2]:
# Open the file
file = open('elections.csv', 'r')

# Create a csv reader object
csv_reader = csv.reader(file)

# Loop through the rows and print our the contents of each row
for row in csv_reader:
    print(row)
    
# Close file
file.close()

['Year', 'Candidate', 'Party', 'Popular vote', 'Result', '%']
['1824', 'Andrew Jackson', 'Democratic-Republican', '151271', 'loss', '57.21012204']
['1824', 'John Quincy Adams', 'Democratic-Republican', '113142', 'win', '42.78987796']
['1828', 'Andrew Jackson', 'Democratic', '642806', 'win', '56.20392707']
['1828', 'John Quincy Adams', 'National Republican', '500897', 'loss', '43.79607293']
['1832', 'Andrew Jackson', 'Democratic', '702735', 'win', '54.57478905']
['1832', 'Henry Clay', 'National Republican', '484205', 'loss', '37.6036283']
['1832', 'William Wirt', 'Anti-Masonic', '100715', 'loss', '7.821582644']
['1836', 'Hugh Lawson White', 'Whig', '146109', 'loss', '10.00598542']
['1836', 'Martin Van Buren', 'Democratic', '763291', 'win', '52.27247202']
['1836', 'William Henry Harrison', 'Whig', '550816', 'loss', '37.72154257']
['1840', 'Martin Van Buren', 'Democratic', '1128854', 'loss', '46.94878676']
['1840', 'William Henry Harrison', 'Whig', '1275583', 'win', '53.05121324']
['1844', 'Henry Clay', 'Whig', '1300004', 'loss', '49.250523']
['1844', 'James Polk', 'Democratic', '1339570', 'win', '50.749477']
['1848', 'Lewis Cass', 'Democratic', '1223460', 'loss', '42.55222948']
['1848', 'Martin Van Buren', 'Free Soil', '291501', 'loss', '10.13847404']
['1848', 'Zachary Taylor', 'Whig', '1360235', 'win', '47.30929648']
['1852', 'Franklin Pierce', 'Democratic', '1605943', 'win', '51.01316828']
['1852', 'John P. Hale', 'Free Soil', '155210', 'loss', '4.930283235']
['1852', 'Winfield Scott', 'Whig', '1386942', 'loss', '44.05654848']
['1856', 'James Buchanan', 'Democratic', '1835140', 'win', '45.30608033']
['1856', 'John C. Frémont', 'Republican', '1342345', 'loss', '33.1399187']
['1856', 'Millard Fillmore', 'American', '873053', 'loss', '21.55400097']
['1860', 'Abraham Lincoln', 'Republican', '1855993', 'win', '39.69940846']
['1860', 'John Bell', 'Constitutional Union', '590901', 'loss', '12.63928267']
['1860', 'John C. Breckinridge', 'Southern Democratic', '848019', 'loss', '18.13899765']
['1860', 'Stephen A. Douglas', 'Northern Democratic', '1380202', 'loss', '29.52231122']
['1864', 'Abraham Lincoln', 'National Union', '2211317', 'win', '54.95151243']
['1864', 'George B. McClellan', 'Democratic', '1812807', 'loss', '45.04848757']
['1868', 'Horatio Seymour', 'Democratic', '2708744', 'loss', '47.33469473']
['1868', 'Ulysses Grant', 'Republican', '3013790', 'win', '52.66530527']
['1872', 'Horace Greeley', 'Liberal Republican', '2834761', 'loss', '44.07140636']
['1872', 'Ulysses Grant', 'Republican', '3597439', 'win', '55.92859364']
['1876', 'Rutherford Hayes', 'Republican', '4034142', 'win', '48.47162359']
['1876', 'Samuel J. Tilden', 'Democratic', '4288546', 'loss', '51.52837641']
['1880', 'James B. Weaver', 'Greenback', '308649', 'loss', '3.352343585']
['1880', 'James Garfield', 'Republican', '4453337', 'win', '48.36923406']
['1880', 'Winfield Scott Hancock', 'Democratic', '4444976', 'loss', '48.27842235']
['1884', 'Benjamin Butler', 'Anti-Monopoly', '134294', 'loss', '1.335838283']
['1884', 'Grover Cleveland', 'Democratic', '4914482', 'win', '48.88493303']
['1884', 'James G. Blaine', 'Republican', '4856905', 'loss', '48.31220781']
['1884', 'John St. John', 'Prohibition', '147482', 'loss', '1.467020877']
['1888', 'Alson Streeter', 'Union Labor', '146602', 'loss', '1.288860686']
['1888', 'Benjamin Harrison', 'Republican', '5443633', 'win', '47.85804123']
['1888', 'Clinton B. Fisk', 'Prohibition', '249819', 'loss', '2.19629942']
['1888', 'Grover Cleveland', 'Democratic', '5534488', 'loss', '48.65679866']
['1892', 'Benjamin Harrison', 'Republican', '5176108', 'loss', '42.98410062']
['1892', 'Grover Cleveland', 'Democratic', '5553898', 'win', '46.12139284']
['1892', 'James B. Weaver', 'Populist', '1041028', 'loss', '8.645038376']
['1892', 'John Bidwell', 'Prohibition', '270879', 'loss', '2.24946817']
['1896', 'John M. Palmer', 'National Democratic', '134645', 'loss', '0.969565599']
['1896', 'Joshua Levering', 'Prohibition', '131312', 'loss', '0.945564989']
['1896', 'William Jennings Bryan', 'Democratic', '6509052', 'loss', '46.87105278']
['1896', 'William McKinley', 'Republican', '7112138', 'win', '51.21381663']
['1900', 'John G. Woolley', 'Prohibition', '210864', 'loss', '1.526820586']
['1900', 'William Jennings Bryan', 'Democratic', '6370932', 'loss', '46.13053974']
['1900', 'William McKinley', 'Republican', '7228864', 'win', '52.34263967']
['1904', 'Alton B. Parker', 'Democratic', '5083880', 'loss', '37.68511564']
['1904', 'Eugene V. Debs', 'Socialist', '402810', 'loss', '2.98589688']
['1904', 'Silas C. Swallow', 'Prohibition', '259102', 'loss', '1.920637157']
['1904', 'Theodore Roosevelt', 'Republican', '7630557', 'win', '56.56278726']
['1904', 'Thomas E. Watson', 'Populist', '114070', 'loss', '0.845563062']
['1908', 'Eugene V. Debs', 'Socialist', '420852', 'loss', '2.85086565']
['1908', 'Eugene W. Chafin', 'Prohibition', '254087', 'loss', '1.721193913']
['1908', 'William Jennings Bryan', 'Democratic', '6408979', 'loss', '43.41464003']
['1908', 'William Taft', 'Republican', '7678335', 'win', '52.01330041']
['1912', 'Eugene V. Debs', 'Socialist', '901551', 'loss', '6.004354059']
['1912', 'Eugene W. Chafin', 'Prohibition', '208156', 'loss', '1.386324593']
['1912', 'Theodore Roosevelt', 'Progressive', '4122721', 'loss', '27.45743344']
['1912', 'William Taft', 'Republican', '3486242', 'loss', '23.21846607']
['1912', 'Woodrow Wilson', 'Democratic', '6296284', 'win', '41.93342184']
['1916', 'Allan L. Benson', 'Socialist', '590524', 'loss', '3.194193328']
['1916', 'Charles Evans Hughes', 'Republican', '8548728', 'loss', '46.24077927']
['1916', 'Frank Hanly', 'Prohibition', '221302', 'loss', '1.197040885']
['1916', 'Woodrow Wilson', 'Democratic', '9126868', 'win', '49.36798652']
['1920', 'Aaron S. Watkins', 'Prohibition', '188787', 'loss', '0.708350618']
['1920', 'Eugene V. Debs', 'Socialist', '913693', 'loss', '3.428281615']
['1920', 'James M. Cox', 'Democratic', '9139661', 'loss', '34.29306318']
['1920', 'Parley P. Christensen', 'Farmer–Labor', '265398', 'loss', '0.995803934']
['1920', 'Warren Harding', 'Republican', '16144093', 'win', '60.57450065']
['1924', 'Calvin Coolidge', 'Republican', '15723789', 'win', '54.329113']
['1924', 'John W. Davis', 'Democratic', '8386242', 'loss', '28.97629123']
['1924', 'Robert La Follette', 'Progressive', '4831706', 'loss', '16.69459577']
['1928', 'Al Smith', 'Democratic', '15015464', 'loss', '40.90285321']
['1928', 'Herbert Hoover', 'Republican', '21427123', 'win', '58.36852373']
['1928', 'Norman Thomas', 'Socialist', '267478', 'loss', '0.728623063']
['1932', 'Franklin Roosevelt', 'Democratic', '22821277', 'win', '57.67212542']
['1932', 'Herbert Hoover', 'Republican', '15761254', 'loss', '39.83059395']
['1932', 'Norman Thomas', 'Socialist', '884885', 'loss', '2.236211353']
['1932', 'William Z. Foster', 'Communist', '103307', 'loss', '0.261069276']
['1936', 'Alf Landon', 'Republican', '16679543', 'loss', '36.64828497']
['1936', 'Franklin Roosevelt', 'Democratic', '27752648', 'win', '60.97810669']
['1936', 'Norman Thomas', 'Socialist', '187910', 'loss', '0.412875774']
['1936', 'William Lemke', 'Union', '892378', 'loss', '1.960732572']
['1940', 'Franklin Roosevelt', 'Democratic', '27313945', 'win', '54.87120208']
['1940', 'Norman Thomas', 'Socialist', '116599', 'loss', '0.234236662']
['1940', 'Wendell Willkie', 'Republican', '22347744', 'loss', '44.89456126']
['1944', 'Franklin Roosevelt', 'Democratic', '25612916', 'win', '53.77380141']
['1944', 'Thomas E. Dewey', 'Republican', '22017929', 'loss', '46.22619859']
['1948', 'Claude A. Watson', 'Prohibition', '103708', 'loss', '0.212746692']
['1948', 'Harry Truman', 'Democratic', '24179347', 'win', '49.60153588']
['1948', 'Henry A. Wallace', 'Progressive', '1157328', 'loss', '2.374143781']
['1948', 'Norman Thomas', 'Socialist', '139569', 'loss', '0.286311982']
['1948', 'Strom Thurmond', 'Dixiecrat', '1175930', 'loss', '2.412303942']
['1948', 'Thomas E. Dewey', 'Republican', '21991292', 'loss', '45.11295773']
['1952', 'Adlai Stevenson', 'Democratic', '27375090', 'loss', '44.44631159']
['1952', 'Dwight Eisenhower', 'Republican', '34075529', 'win', '55.32517261']
['1952', 'Vincent Hallinan', 'Progressive', '140746', 'loss', '0.228515799']
['1956', 'Adlai Stevenson', 'Democratic', '26028028', 'loss', '42.17446362']
['1956', 'Dwight Eisenhower', 'Republican', '35579180', 'win', '57.65065384']
['1956', 'T. Coleman Andrews', "States' Rights", '107929', 'loss', '0.174882541']
['1960', 'John Kennedy', 'Democratic', '34220984', 'win', '50.08256141']
['1960', 'Richard Nixon', 'Republican', '34108157', 'loss', '49.91743859']
['1964', 'Barry Goldwater', 'Republican', '27175754', 'loss', '38.65529671']
['1964', 'Lyndon Johnson', 'Democratic', '43127041', 'win', '61.34470329']
['1968', 'George Wallace', 'American Independent', '9901118', 'loss', '13.57121768']
['1968', 'Hubert Humphrey', 'Democratic', '31271839', 'loss', '42.86353667']
['1968', 'Richard Nixon', 'Republican', '31783783', 'win', '43.56524565']
['1972', 'George McGovern', 'Democratic', '29173222', 'loss', '37.67067048']
['1972', 'John G. Schmitz', 'American Independent', '1100868', 'loss', '1.421524015']
['1972', 'Richard Nixon', 'Republican', '47168710', 'win', '60.9078055']
['1976', 'Eugene McCarthy', 'Independent', '740460', 'loss', '0.911648689']
['1976', 'Gerald Ford', 'Republican', '39148634', 'loss', '48.19949876']
['1976', 'Jimmy Carter', 'Democratic', '40831881', 'win', '50.2718996']
['1976', 'Lester Maddox', 'American Independent', '170274', 'loss', '0.209640047']
['1976', 'Roger MacBride', 'Libertarian', '172557', 'loss', '0.212450859']
['1976', 'Thomas J. Anderson', 'American', '158271', 'loss', '0.194862045']
['1980', 'Barry Commoner', 'Citizens', '233052', 'loss', '0.270182115']
['1980', 'Ed Clark', 'Libertarian', '921128', 'loss', '1.067883181']
['1980', 'Jimmy Carter', 'Democratic', '35480115', 'loss', '41.13284806']
['1980', 'John B. Anderson', 'Independent', '5719850', 'loss', '6.631143134']
['1980', 'Ronald Reagan', 'Republican', '43903230', 'win', '50.89794351']
['1984', 'David Bergland', 'Libertarian', '228111', 'loss', '0.247245489']
['1984', 'Ronald Reagan', 'Republican', '54455472', 'win', '59.02332553']
['1984', 'Walter Mondale', 'Democratic', '37577352', 'loss', '40.72942898']
['1988', 'George H. W. Bush', 'Republican', '48886597', 'win', '53.5188446']
['1988', 'Lenora Fulani', 'New Alliance', '217221', 'loss', '0.237803767']
['1988', 'Michael Dukakis', 'Democratic', '41809074', 'loss', '45.77069118']
['1988', 'Ron Paul', 'Libertarian', '431750', 'loss', '0.472660454']
['1992', 'Andre Marrou', 'Libertarian', '290087', 'loss', '0.278516275']
['1992', 'Bill Clinton', 'Democratic', '44909806', 'win', '43.11848477']
['1992', 'Bo Gritz', 'Populist', '106152', 'loss', '0.101917906']
['1992', 'George H. W. Bush', 'Republican', '39104550', 'loss', '37.54478351']
['1992', 'Ross Perot', 'Independent', '19743821', 'loss', '18.95629754']
['1996', 'Bill Clinton', 'Democratic', '47400125', 'win', '49.29693808']
['1996', 'Bob Dole', 'Republican', '39197469', 'loss', '40.766036']
['1996', 'Harry Browne', 'Libertarian', '485759', 'loss', '0.505197641']
['1996', 'Howard Phillips', 'Taxpayers', '184656', 'loss', '0.192045388']
['1996', 'John Hagelin', 'Natural Law', '113670', 'loss', '0.118218738']
['1996', 'Ralph Nader', 'Green', '685297', 'loss', '0.712720563']
['1996', 'Ross Perot', 'Reform', '8085294', 'loss', '8.408843598']
['2000', 'Al Gore', 'Democratic', '50999897', 'loss', '48.49181314']
['2000', 'George W. Bush', 'Republican', '50456002', 'win', '47.97466592']
['2000', 'Harry Browne', 'Libertarian', '384431', 'loss', '0.36552537']
['2000', 'Pat Buchanan', 'Reform', '448895', 'loss', '0.426819146']
['2000', 'Ralph Nader', 'Green', '2882955', 'loss', '2.741176421']
['2004', 'David Cobb', 'Green', '119859', 'loss', '0.098088334']
['2004', 'George W. Bush', 'Republican', '62040610', 'win', '50.77182439']
['2004', 'John Kerry', 'Democratic', '59028444', 'loss', '48.30677508']
['2004', 'Michael Badnarik', 'Libertarian', '397265', 'loss', '0.325107519']
['2004', 'Michael Peroutka', 'Constitution', '143630', 'loss', '0.117541674']
['2004', 'Ralph Nader', 'Independent', '465151', 'loss', '0.380663003']
['2008', 'Barack Obama', 'Democratic', '69498516', 'win', '53.02350971']
['2008', 'Bob Barr', 'Libertarian', '523715', 'loss', '0.399565473']
['2008', 'Chuck Baldwin', 'Constitution', '199750', 'loss', '0.152398162']
['2008', 'Cynthia McKinney', 'Green', '161797', 'loss', '0.123442129']
['2008', 'John McCain', 'Republican', '59948323', 'loss', '45.7372426']
['2008', 'Ralph Nader', 'Independent', '739034', 'loss', '0.563841917']
['2012', 'Barack Obama', 'Democratic', '65915795', 'win', '51.25848423']
['2012', 'Gary Johnson', 'Libertarian', '1275971', 'loss', '0.992240773']
['2012', 'Jill Stein', 'Green', '469627', 'loss', '0.365198784']
['2012', 'Mitt Romney', 'Republican', '60933504', 'loss', '47.38407621']
['2016', 'Darrell Castle', 'Constitution', '203091', 'loss', '0.149639515']
['2016', 'Donald Trump', 'Republican', '62984828', 'win', '46.40786214']
['2016', 'Evan McMullin', 'Independent', '732273', 'loss', '0.539546197']
['2016', 'Gary Johnson', 'Libertarian', '4489235', 'loss', '3.307714026']
['2016', 'Hillary Clinton', 'Democratic', '65853514', 'loss', '48.52153918']
['2016', 'Jill Stein', 'Green', '1457226', 'loss', '1.073698944']
['2020', 'Joseph Biden', 'Democratic', '81268924', 'win', '51.3115152']
['2020', 'Donald Trump', 'Republican', '74216154', 'loss', '46.8585423']
['2020', 'Jo Jorgensen', 'Libertarian', '1865724', 'loss', '1.1779795']
['2020', 'Howard Hawkins', 'Green', '405035', 'loss', '0.25573071']

So, let's say that we're asked to print the name of the candidate with the lowest popular vote percentage (%) in the year 1996 election. The following code is how we could do this using the pure Python and the `csv` module.

In [3]:
file = open('elections.csv', 'r')
csv_reader = csv.reader(file)

row_count = 0
name = None
popular_vote = 100

for row in csv_reader:
    
    # Skip first row (column names)
    if row_count > 0:
        
        # row[0] is the column "Year"
        if row[0] == '1996':    
            
            # row[5] is the column "%"
            if float(row[5]) < popular_vote:
                popular_vote = float(row[5])
                
                # row[1] is the column "Candidate"
                name = row[1]
   
    row_count += 1
    
print('Candidate', name, 'had the lowest popular vote in 1996, which was', popular_vote, '%.')
    
file.close()

Candidate John Hagelin had the lowest popular vote in 1996, which was 0.118218738 %.

The `csv` module allowed us to get the desired output but the code has some limitations. For starts, it's a lot of code for a fairly simple query. Additionally, we are accessing the columns by an index, which makes the code challenging to interpret and potentially prone to error. Lastly, all the data is imported as strings, which means we must convert to a numeric data type for certain columns.

In this lecture, we will introduce the `Pandas` library, which is the standard in academia and industry for working with tabular data in Python. 

If you're using Anaconda, this package will likely be installed in your `(base)` environment but if not, you can run this code in a notebook cell to install.

```python

!pip install pandas
```

First, let's import `Pandas` and give it the name `pd`.

In [4]:
import pandas as pd

Now, let's try to write some code to accomplish the above task.

Let's first load the `csv` file and print the first 5 rows.

In [11]:
elections = pd.read_csv('elections.csv')
elections.head(20)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
5,1832,Henry Clay,National Republican,484205,loss,37.603628
6,1832,William Wirt,Anti-Masonic,100715,loss,7.821583
7,1836,Hugh Lawson White,Whig,146109,loss,10.005985
8,1836,Martin Van Buren,Democratic,763291,win,52.272472
9,1836,William Henry Harrison,Whig,550816,loss,37.721543
10,1840,Martin Van Buren,Democratic,1128854,loss,46.948787
11,1840,William Henry Harrison,Whig,1275583,win,53.051213
12,1844,Henry Clay,Whig,1300004,loss,49.250523
13,1844,James Polk,Democratic,1339570,win,50.749477
14,1848,Lewis Cass,Democratic,1223460,loss,42.552229
15,1848,Martin Van Buren,Free Soil,291501,loss,10.138474
16,1848,Zachary Taylor,Whig,1360235,win,47.309296
17,1852,Franklin Pierce,Democratic,1605943,win,51.013168
18,1852,John P. Hale,Free Soil,155210,loss,4.930283
19,1852,Winfield Scott,Whig,1386942,loss,44.056548

For starters, this is a much nicer view for getting a quick snap shot of our dataset.

But what data type is `elections`?

In [ ]:
print(type(elections))
print(elections.shape)
print(elections.columns)
print('---')
print(elections['Candidate'])

<class 'pandas.DataFrame'>
(182, 6)
Index(['Year', 'Candidate', 'Party', 'Popular vote', 'Result', '%'], dtype='str')
---
0         Andrew Jackson
1      John Quincy Adams
2         Andrew Jackson
3      John Quincy Adams
4         Andrew Jackson
             ...
177           Jill Stein
178         Joseph Biden
179         Donald Trump
180         Jo Jorgensen
181       Howard Hawkins
Name: Candidate, Length: 182, dtype: str

Hmmmm.... what is a `DataFrame`? More on this later.

Now, let's try to find the 1996 candidate with the lowest popular vote %.

In [7]:
worse_candidate = elections.loc[elections['Year'] == 1996, :].sort_values('%', ascending=True).iloc[0]
print(worse_candidate)

Year                    1996
Candidate       John Hagelin
Party            Natural Law
Popular vote          113670
Result                  loss
%                   0.118219
Name: 148, dtype: object

And what data type is `worse_candidate`?

In [8]:
print(type(worse_candidate))

<class 'pandas.Series'>

Hmmmm.... what is a `Series`? More on this later.

Now, let's print out the results as we did with the prvious example.

In [9]:
print('Candidate', worse_candidate['Candidate'], 'had the lowest popular vote in 1996, which was', worse_candidate['%'], '%.')

Candidate John Hagelin had the lowest popular vote in 1996, which was 0.118218738 %.

So, how did we do? Well, we have reduced our code from 14 lines to 3. We are accessing columns by their name, not their position. Lastly, the data has been imported and automatically converted to the most likely data type. As you can see below, `'Candidate'` is a `string` and `'%'` is a `float`.

In [ ]:
elections.dtypes

Note: `object` is a `string` and `dtypes` is a `DataFrame` attribute, which outputs a `Series` showing the name of which column and the corresponding data type.

Now, let's learn how this `Pandas` library works.

<a id='section2'></a>
## 2. DataFrames
A `DataFrame` is a 2-dimensional labelled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. `DataFrames` were first introduced in the [**R Programming Language**](https://www.r-project.org/) and are generally the most commonly used pandas object. **Pandas** is the most popular Python package for working with `DataFrames`.
<br>
<img src="images/dataframe_overview.png" alt="drawing" width="850"/>
<br>

In this lecture, we will see how a `DataFrame` can be created from scratch or loaded from a file.

### How to Create a `DataFrame`
We can also create a `DataFrame` in a variety of ways. Here, we cover the following:

1. From a CSV file
1. Using a list and column names
1. From a dictionary

#### Creating a `DataFrame` from a CSV file
For loading data into a `DataFrame`, `pandas` has a number of very useful file reading tools. We'll be using `read_csv` today to load data from a CSV file into a `DataFrame` object.

In [17]:
elections = pd.read_csv("elections.csv")
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

Because we did not specify a column which should be used as the `index`, `pandas` creates a default index for us. The default index starts and zero and increases by 1 (`0, 1, 2, 3, 4, ...`).

#### Creating a `DataFrame` using a list and column names
You can create a `DataFrame` using two lists. One list will contain the column names as seen below.

In [18]:
columns = ['Salary', 'Job Title']

The other list will contain the data. Each sub-list represents a row and the number of items in the sub-list must be equal to the number of items in the `columns` list.

In [19]:
data = [
    [110000, 'Professor'],
    [90000, 'Developer'],
    [130000, 'Electrician']
]

We can then use the pd.DataFrame constructor by passing the columns list to the `columns` parameter and the data list to the `data` parameter.

In [20]:
salaries = pd.DataFrame(data=data, columns=columns)
salaries

   Salary    Job Title
0  110000    Professor
1   90000    Developer
2  130000  Electrician

Because we did pass an argument to the `index` parameter, `pandas` creates a default index for us. I could use a custom `index` as follows.

In [21]:
salaries = pd.DataFrame(index=[10, 12, 20], data=data, columns=columns)
salaries

    Salary    Job Title
10  110000    Professor
12   90000    Developer
20  130000  Electrician

In [33]:
high_sala = salaries[salaries['Salary'] >= 100000]
high_sala

    Salary    Job Title
10  110000    Professor
20  130000  Electrician

#### Creating a `DataFrame` from a dictionary
You can create a `DataFrame` using a dictionary where the keys are the column names and the values are lists. The length of each list must be the same.

In [34]:
df_dict_1 = pd.DataFrame({"Fruit":["Strawberry", "Orange", "Banana"], 
                          "Price":[5.49, 3.99, 9.99]})
df_dict_1

        Fruit  Price
0  Strawberry   5.49
1      Orange   3.99
2      Banana   9.99

Notice how the `"Fruit"` list and the `"Price"` list have the same number of items in them (3).

You can also create a `DataFrame` using a list of dictionaries where each dictionary holds the data for a given row.

In [32]:
df_dict_2 = pd.DataFrame([{"Fruit": "Strawberry", "Price": 5.49}, 
                          {"Fruit": "Orange", "Price": 3.99},
                          {"Fruit": "Banana", "Price": 9.99}])
df_dict_2

        Fruit  Price
0  Strawberry   5.49
1      Orange   3.99
2      Banana   9.99

### `DataFrame` attributes: `index`, `columns`,`shape`
The figure below displays the different components of a DataFrame, which include: `indices`, `columns`, `axes` (more on these later), and `Series`.
<br>
<img src="images/DataFrame.png" alt="drawing" width="450"/>
<br>
Let's check out our `elections` `DataFrame` again.

In [23]:
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

### `index`
The `index` can be thought of as row labels. They can be numeric but they do not have to be. They could also be strings or datetimes, for example. If the `index` of a DataFrame is numeric, it does not have to be for the form `0, 1, 2, 3, 4, ...`.

#### `index` as a monotonic sequence of integers
The example below for `elections` is likely the expected behaviour when thinking about row indices of a data table.

In [24]:
elections.index

RangeIndex(start=0, stop=182, step=1)

`index` returns a `RangeIndex()` object, which shows the start, end and step size of the row indices. `RangeIndex` is a memory-saving object used for representing monotonic ranges. This is similar to how we represent a sequence of integers using the `range` function in Python. For example, `range(0, 182, 1)`.

#### Converting a column into the index
Sometimes, it's advantageous to set a column in your DataFrame as the index. Consider our `elections` `DataFrame` again.

In [25]:
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

We can set the `"Year"` column as the index.

In [ ]:
elections = elections.set_index('Year')
elections

And we can reset the `index` using a monotonic range.

In [ ]:
elections = elections.reset_index()
elections

#### `index` as an array of numeric values
Let's go back to `"Year"` being the `index`.

In [ ]:
elections = elections.set_index('Year')
elections

One important property of `index` is that these row labels do not have to be unique, which probably seems counterintuitive. As we can see from the example above, there is more than one row with the index `2020`.

Because the index is not longer a monotonic range, the `RangeIndex()` object can no longer be used to represent it.

In [ ]:
elections.index

Instead, we get a list of index values.

#### `index` as an array of non-numeric values
In the example below, you can see that we can also create an `index` using non-numeric data.

In [ ]:
elections = elections.reset_index()
elections = elections.set_index('Candidate')
elections

In [ ]:
elections = elections.reset_index()

### `columns`
`columns` are column labels in the same way the `indices` are row labels. We can get a list of `column` names using the following code.

In [ ]:
elections.columns

One special characteristic of `columns` is that they must be unique. See what happens when we try to make a `DataFrame` with all columns of the same name.

In [ ]:
df_dict_3 = pd.DataFrame({"Fruit":["Strawberry", "Orange", "Banana"], 
                          "Fruit":[0, 1, 2],
                          "Fruit":['a', 'b', 'c']})
df_dict_3

You can see that only one `column` is added to the `DataFrame` and the `data` is from the last item in the dictionary.

### `shape`
`shape` is a `tuple` where the first item is the number of rows and the second item is the number of columns.
```python
>>> dataframe.shape
(num_rows, num_columns)
```

In [35]:
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [36]:
elections.shape

(182, 6)

In [37]:
df_dict_2 = pd.DataFrame([{"Fruit": "Strawberry", "Price": 5.49}, 
                          {"Fruit": "Orange", "Price": 3.99},
                          {"Fruit": "Banana", "Price": 9.99}])
df_dict_2

        Fruit  Price
0  Strawberry   5.49
1      Orange   3.99
2      Banana   9.99

In [41]:
df_dict_2.shape
df_dict_2.max(axis=0)

Fruit    Strawberry
Price          9.99
dtype: object

<a id='section3'></a>
## 3. Breakout Session 1
Given the data below, create a `DataFrame` with the columns `phone_number`, `job`, and `years`. The index should be `"name"` with the data coming from `data1`. There should be 4 rows in the `DataFrame`. Below is an example of the expected output of your code.

<img src="images/breakout_session_1.png" width="400" style="margin:auto"/>

In [ ]:
data1 = {'name': ['John', 'Susan', 'Omid', 'Ava']}
data2 = {'phone_number': ['234-5678', '123-4567', '111-4444', '456-0987']}
data3 = {'job': ['Pizza Delivery', 'Teacher', 'Chemist', 'Coder']}
data4 = {'years_of_experience': [10, 2, 5, 8]}

# Write your code here
...

# Display DataFrame
df1

<a id='section4'></a>
## 4. Series
A `Series` is a 1-D labelled array of data. We can think of it as a column of data like you may have seen in an excel spreadsheet.

### Creating a new `Series` object
Below, we create a `Series` object.

In [42]:
my_series = pd.Series(["welcome", "to", "APS106"])
print(my_series)

0    welcome
1         to
2     APS106
dtype: str

Series have three main components, `index`, `name`, `data` (also referred to as `values`) as you can see in the diagram below. As you can see, `DataFrames` are collections of `Series`. Therefore, a helpful way to think of a `Series` is as a column from a table of data, like an Excel sheet.

<img src="images/Pandas_Series.png" width="600" style="margin:auto"/>


So, for our new `Series` `my_series`, let's check out these attributes (`index`, `name`, `data`).

**name**

In [43]:
print(my_series.name)

None

We never gave our `Series` a name, so by default, its `None`.

**data (values)**

In [44]:
print(my_series.values)

<StringArray>
['welcome', 'to', 'APS106']
Length: 3, dtype: str

We passed this data to our `Series` constructor (`my_series = pd.Series(["welcome", "to", "APS106"])`).

**index**

In [45]:
print(my_series.index)

RangeIndex(start=0, stop=3, step=1)

In the example above, `Pandas` automatically generated an `Index` of integer labels. The first item in the `Series` has `index = 0`, the second item has `index = 1` and so on. We can also create a `Series` object by providing a custom Index. In the case of our example, rather than the index being a long list of monotonically increasing integers, `Pandas` has created a `RangeIndex` object to represent the same information in a simpler and more compact format. `RangeIndex(start=0, stop=3, step=1)` is the same as `[0, 1, 2]` but in the case where you have millions of items in your `Series`, it's much more efficient. This should look familiar to you given `RangeIndex(start=0, stop=3, step=1)` would be very similar to `range(0, 3, 1)` that we learned in **Week 6**. 

Here is an example where we are specifying an `index`, `data`, and `name` when we create a new `Series`.

In [46]:
my_series = pd.Series(data=[20000, 21000, 100000, 88000, 101000], 
                      index=["Seb", "Ben", "Katia", "Joseph", "Tamara"], 
                      name="salary")
print(my_series)

Seb        20000
Ben        21000
Katia     100000
Joseph     88000
Tamara    101000
Name: salary, dtype: int64

We can see all the `Series` information in the print-out and we can also see it by using the attributes below.

In [47]:
print(my_series.name)
print(my_series.values)
print(my_series.index)

salary
[ 20000  21000 100000  88000 101000]
Index(['Seb', 'Ben', 'Katia', 'Joseph', 'Tamara'], dtype='str')

Now, because our index is no longer monotonically increasing integers (e.g. [0, 2, 4, 6, 8]), you can see that the `RangeIndex` object is no longer able to be used to represent the `index`. For this example, the `index` is simply a list of the index values `["Seb", "Ben", "Katia", "Joseph", "Tamara"]`.

**Note:** The idea of having of having non-numeric indices is new and a bit strange. We'll get into this more shortly.

After a `Series` has been created, we can reassign the `Index` of a `Series` to a new `Index`.

In [ ]:
my_series.index = ['Goodfellow', 'Kinsella', 'Ossetchkina', 'Sebastian', 'Kecman']
print(my_series)

We can also do this for `name`.

In [ ]:
my_series.name = 'income'
print(my_series)

But not for `data` (`values`).

In [ ]:
my_series.values = [0, 0, 0, 0, 0]
print(my_series)

More on how to update column data next lecture.

<a id='section5'></a>
## 5. Data Extraction
We can use `.head()` to return the first 5 rows of a DataFrame or `.tail()` to return the last 5 rows of a `DataFrame`.

In [ ]:
elections = pd.read_csv("elections.csv")
elections

In [ ]:
elections.head()

In [ ]:
elections.tail()

If you'd like to see the first `10` rows, simply pass `10` as an argument.

In [ ]:
elections.head(10)

### Label-Based Extraction using `.loc`
The `.loc` method in Pandas is primarily used for label-based indexing. It allows you to select data from a DataFrame based on labels or boolean arrays. The `.loc` method takes two arguments. The first is a row selection and the second is a column selection in the following form:
```python
dataframe.loc(row-selection, column-selection)
```

These arguments to `.loc`, `row-selection` and `column-selection` can be:
- A list.
- A slice (syntax is inclusive of the right-hand side of the slice).
- A single value.

Consider our `elections` DataFrame.

In [ ]:
elections.head()

#### Selection using a list.
The first argument is a list of row labels. These would be values in `.index`. The second argument is a list of column labels. These would be values in `.columns`.
```python
dataframe.loc([List-of-row-labels], [List-of-column-labels])
```
These are the options for the row labels:

In [ ]:
elections.index

Basically, numbers between 0 and 181.

In [ ]:
print(list(elections.index)[0:10])

In [ ]:
print(list(elections.index)[-10:])

And these are the options for columns labels.

In [ ]:
elections.columns

So, lets try this out.

In [ ]:
elections.loc[[87, 25, 179], ["Year", "Candidate", "Result"]]

#### Selection using a slice
In Pandas, the `:` slice in the `.loc` method is used to select rows and/or columns by label. It represents a range of labels or all labels along a particular axis (rows or columns). Row and column slices can be passed to the `.loc` method in the following way.
```python
df.loc[row_label_slice, column_label_slice]
```
- `row_label_slice`: A slice or a sequence of labels representing the range of rows to select.
- `column_label_slice`: A slice or a sequence of labels representing the range of columns to select.

**Slice of Labels:** If you pass a slice of labels (e.g., `start_label:end_label`), `.loc` selects all rows or columns with labels within the specified range, including both the start and end labels. For example:

In [ ]:
elections.loc[80:85, "Candidate":"%"]

In this case, our row slice was `80:85`, which produced the following list of row labels `[80, 81, 82, 83, 84, 85]` and our column slice `"Popular vote":"%"` will produce the following list of column labels `["Candidate", "Party", "Popular vote", "Result", "%"]`.

You can also add a step size with the following syntax: `start_label:end_label:step_size`. For example, using a step size of `2` for the previous example would produce the following output.

In [ ]:
elections.loc[80:85:2, "Candidate":"%":2]

**Important:** Compared to what we have previously learned with regards to slicing `strings`, `lists`, `tuples`, etc., the start and stop labels for `.loc` are inclusive. You'll recall that for `string` slicing, `string[0:5]` will include indices `0, 1, 2, 3, 4` and NOT `5`. In the example above, you'll notice row label `85` and column label `"%"` are included.

`.loc` also supports a negative step size.

In [ ]:
elections.loc[80:85:2, "%":"Candidate":-1]

The one area where you can run into an error is when slicing row labels where there are non-unique values. Let's create a dummy DataFrame to show this behavior.

In [ ]:
elections_test = elections.loc[80:90, "Year":"%"]
elections_test.index = [0, 1, 2, 3, 2, 5, 10, 12, 13, 8, 30]
elections_test

Now we have an `index` that is NOT MONOTONIC where monotonically increasing integers are a sequence of numbers where each number is greater than or equal to the preceding number.

In [ ]:
elections_test.loc[2:8, "Year":"Party"]

As you can see, we get an error. This means that when our row labels or column labels are not monotonically increasing or decreasing, we cannot use slicing.

**Selection of all Labels:**  If you use `:` alone, `.loc` selects all rows or columns. For example, if I want to select all columns but only a few rows, we could do the following:

In [ ]:
elections.loc[[3, 10, 50], :]

**Selection of a single value:**  You can pass a single row or column label into the row or column selection arguments of the `loc` method.

Below is an example of selecting a single value in a table.

In [ ]:
elections.loc[0, 'Candidate']

Below is an example of selecting a single row in a table.

In [ ]:
elections.loc[0, :]

You can see the `type` is a `Series`, which Pandas uses to represent 1-D data, which a row is what a row is.

In [ ]:
type(elections.loc[0, :])

However, if you want `.loc` to return a `DataFrame` with a single row, then you need to pass in a list of row labels with only one row label in it.

In [ ]:
elections.loc[[0], :]

In [ ]:
type(elections.loc[[0], :])

Below is an example of selecting a single column in a table is a `Series`.

In [ ]:
elections.loc[:, 'Candidate']

And the same example but where a `DataFrame` with one column is returned.

In [ ]:
elections.loc[:, ['Candidate']]

### Integer-Based Extraction Using iloc `.iloc`
In Pandas, the `.iloc` method is used for integer-based indexing, allowing you to select rows and/or columns by their integer position within the DataFrame. It is similar to Python's native indexing we use for `lists`, `string`, `tuples`, and `range`.

- When using `.iloc`, integer indexes are used to select rows and columns.
- Slices in `.iloc` are exclusive of the end index, meaning the row or column at the end index is not included in the selection.
- Negative integer indexes can be used to select rows or columns from the end of the `DataFrame`.
- `.iloc` provides a way to access `DataFrame` elements based on their integer position, which can be useful when you want to select rows or columns by their position rather than by their labels.

The figure below shows the differences between `loc` and `iloc`.

<img src="images/iloc_loc.png" width="900" style="margin:auto"/>

Let's check out our `elections` dataset again.

In [ ]:
elections.head()

Below are some examples of using `iloc`.

In [ ]:
elections.iloc[2:, 3:5]

In [ ]:
elections.iloc[::2, 3:5]

In [ ]:
elections.iloc[5:-1, 3:5]

#### Caution
We will use both `.loc` and `.iloc` in the course. `.loc` is generally preferred for a number of reasons, for example: 

1. It is harder to make mistakes since you have to literally write out what you want to get.
2. Code is easier to read because the reader doesn't have to know e.g. what column **#31** represents.
3. It is robust against permutations of the data, e.g. the Social Security administration switches the order of two columns.

However, `iloc` is sometimes more convenient. We'll provide examples of when iloc is the superior choice.

### Data Extraction From A `Series` using `.loc` and `iloc`.
`loc` and `iloc` can be used in the same way for a `Series`. The only difference is that they do not require row and column selections because a `Series` is 1D. Let's go back to our `Series` example.

In [ ]:
my_series = pd.Series(data=[20000, 21000, 100000, 88000, 101000], 
                      index=["Seb", "Ben", "Katia", "Joseph", "Tamara"], 
                      name="salary")
print(my_series)

In [ ]:
my_series.loc['Ben']

In [ ]:
my_series.loc['Ben':'Joseph']

In [ ]:
my_series.iloc[2]

In [ ]:
my_series.iloc[1:4]

<a id='section6'></a>
## 6. Breakout Session 2
You have been provided with a `DataFrame` containing information about students' scores in different subjects.

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Math': [80, 85, 90, 95, 75],
    'Science': [75, 90, 85, 80, 95],
    'English': [85, 80, 75, 70, 90],
    'History': [90, 85, 80, 75, 85]
}

df = pd.DataFrame(data)
df

#### Question 1
Select the scores of the last 2 students in `"Math"` and `"Science"` using `.loc`.

In [ ]:
...

#### Question 2
Select the scores of the 2nd, 3rd, and 4th students in `"English"` and `"History"` using `.iloc`.

In [ ]:
...

#### Question 3
Select the scores of the 1st, 3rd, and 5th students in all subjects using `.iloc`.

In [ ]:
...

#### Question 4
Select the scores of all students in `"Math"` and `"Science"` using `.loc`.

In [ ]:
...

#### Question 5
Create a new `DataFrame` including all the rows but when the columns reorder in reverse order using `.loc` and slicing.

In [ ]:
...

<a id='section7'></a>
## 7. Looping
There are MANY ways to loop over a `DataFrame`. Some are very fast and others very slow but for `APS106` we will learn two methods, one that relies on `.loc` and the other that relies on `.iloc`. 

Let's reload our trusty elections dataset.

In [ ]:
elections = pd.read_csv("elections.csv")
elections.head()

### Looping over row labels (`.loc`)
In the code below, we are looping over the row labels and then using them to access the candidate using `.loc`. The candidate is saved as a string and then the first name is printed in all lower-case.

In [ ]:
for row_label in elections.index:
    candidate = elections.loc[row_label, 'Candidate']
    print(candidate.split(' ')[0].lower())

### Looping over row label positions (`.iloc`)
In the code below, we are looping over the row label positions and then using them to access the candidate using `.iloc`. The candidate is saved as a string and then the first name is printed in all lower-case.

In [ ]:
for row_id in range(elections.shape[0]):
    candidate = elections.iloc[row_id, 1]
    print(candidate.split(' ')[0].lower())

### Looping over a `Series`
We can loop over the values in a `Series` as follows.

In [ ]:
for item in my_series:
    print(item)

Or, we could loop through the indices and then use them to access the values.

In [ ]:
for index in my_series.index:
    print(index, my_series.loc[index])

<a id='section8'></a>
## 8. Saving DataFrames
In Pandas, saving `DataFrames` as `CSV` (Comma Separated Values) files is a straightforward process and can be done using the `to_csv()` function. This function allows you to save the contents of a `DataFrame` to a `CSV` file with various options for customization.

Let's create a custom `DataFrame`.

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Department': ['HR', 'Engineering', 'Marketing']}
df = pd.DataFrame(data)
df.head()

To save a `DataFrame` all we need is to specify the name of the file we're saving.

In [ ]:
df.to_csv('example.csv')

If we don't want to include the `index`, simply pass `False` to the `index` parameter.

In [ ]:
df.to_csv('example.csv', index=False)